---
title: "Bacteria_helper"
author: "HHN"
date: "2023-11-13"
output: html_document
editor_options: 
  chunk_output_type: inline
---

## Library used here:

```{r library,  message=FALSE, warning=FALSE}

library("ggplot2")
library("tibble")
library("tidyr")
library("ggpubr")
library("agricolae")
library("multcompView")

```

## Read Files
```{r Read files, message=FALSE, warning=FALSE}
bacteria1 <- read.csv2(file = "./Data/helper_combined.csv", header = TRUE, dec = ",", sep = ";", fileEncoding="UTF-8-BOM")
bacteria1 = as_tibble(bacteria1)
bacteria1 = na.omit(bacteria1)
bacteria1 = bacteria1[,1:6]
bacteria1$treatment = factor(bacteria1$treatment , levels = c("Mock", "E2"))
bacteria2 = unite(bacteria1, treatment, day, col = "Treatment_day", sep = "_")
bacteria2 = unite(bacteria2, line, Treatment_day, col = "Line_Treatment_day", sep = "_")

```

## Statistics

```{r Tuckey Test, include=TRUE, echo=TRUE, message=TRUE}
activity_treatment2 = aov(bacteria1$cfu ~ bacteria1$line*bacteria1$treatment*bacteria1$day + bacteria1$batch)
summary(activity_treatment2)
Tuckey <- TukeyHSD(activity_treatment2)
test_value <- HSD.test(activity_treatment2, "bacteria1$line*bacteria1$treatment*bacteria1$day", group = TRUE,
                       console=TRUE)
multcompLetters4(activity_treatment2, Tuckey)


activity_treatment = aov(bacteria2$cfu ~ bacteria2$Line_Treatment_day)
Tuckey <- TukeyHSD(activity_treatment)
test_value <- HSD.test(activity_treatment, "bacteria2$Line_Treatment_day", group = TRUE,
                       console=TRUE)


sig = data.frame(Line = row.names(test_value[[5]]), sig_letter = test_value[[5]][[2]])
sig$Line = factor(sig$Line, levels = c("SETI_Mock_0 days", "SETI_E2_0 days", "SETIeds1_Mock_0 days", "SETIeds1_E2_0 days", "SETIhelperless_Mock_0 days", "SETIhelperless_E2_0 days", 
                                       "SETIadrs_Mock_0 days", "SETIadrs_E2_0 days", "SETInrg1_Mock_0 days", "SETInrg1_E2_0 days",
                                       "SETI_Mock_3 days", "SETI_E2_3 days", "SETIeds1_Mock_3 days", "SETIeds1_E2_3 days", "SETIhelperless_Mock_3 days", "SETIhelperless_E2_3 days", 
                                       "SETIadrs_Mock_3 days", "SETIadrs_E2_3 days", "SETInrg1_Mock_3 days", "SETInrg1_E2_3 days"))

line_order = order(sig$Line, levels = c("SETI_Mock_0 days", "SETI_E2_0 days", "SETIeds1_Mock_0 days", "SETIeds1_E2_0 days", "SETIhelperless_Mock_0 days", "SETIhelperless_E2_0 days", 
                                        "SETIadrs_Mock_0 days", "SETIadrs_E2_0 days", "SETInrg1_Mock_0 days", "SETInrg1_E2_0 days",
                                        "SETI_Mock_3 days", "SETI_E2_3 days", "SETIeds1_Mock_3 days", "SETIeds1_E2_3 days", "SETIhelperless_Mock_3 days", "SETIhelperless_E2_3 days", 
                                        "SETIadrs_Mock_3 days", "SETIadrs_E2_3 days", "SETInrg1_Mock_3 days", "SETInrg1_E2_3 days"))
sig_ordered = sig[line_order,]

```


## Finished Figure

```{r Plotting, include=TRUE, message=FALSE, echo=TRUE}
######################## Boxplot Line Treatment separate

#################Part1 Image size: 1182×829

dlab_theme = theme(axis.title.y = element_text(margin = margin(r = 10)), text = element_text(size=12), axis.text = element_text(size=12),
        axis.text.x = element_text(margin = margin(t = 5), size = 12, colour = "black", angle = 20, hjust=1),
        axis.text.y = element_text(color = "black"),
        axis.line = element_blank(),
        axis.ticks = element_line(size = 1),
        axis.title.x = element_blank(),
        legend.position="bottom", 
        legend.text= element_text(size = 12),
        legend.title = element_text(size = 12),
        panel.background = element_blank(),
        panel.spacing.x = unit(1, "lines"),
        panel.spacing.y=unit(0,"lines"),
        panel.grid =  element_blank(),
        #panel.grid.major.y =  element_line(colour = "#999999"),
        panel.grid.minor.y =  element_blank(),
        panel.border = element_rect(fill = NA, color = "black", linewidth = 1),
        strip.background =element_rect(fill="white"),
        strip.text.x = element_text(size = 12, hjust = 0.5))

plot1 = ggplot(bacteria1, mapping = aes(x = line, y = cfu)) +
  geom_boxplot(aes(fill = treatment), outlier.shape = NA) +
  geom_jitter(mapping = aes(shape = batch, group = treatment), fill = "grey", color = "black", size=1, position = position_jitterdodge(jitter.width = 0.3)) +
  ylim(3, 10) +
  scale_fill_manual(values = c("#F93D3D", "#0072B2"),
                    name = "Treatment", labels = c("Mock", "ETI"))  +
  scale_shape_manual(name = "Batches", values = unique(bacteria1$batch_aes), labels = c("B1","B2","B3")) +
  #scale_shape_discrete(position = position_identity()) +
  labs(y = expression(bold(atop("Bacteria Count",paste("(log(CFU/",cm^{"2"},"))")))), x = "Line") +
  dlab_theme +
  facet_wrap(~as.factor(day)) +
  scale_x_discrete(limits = c("SETI", "SETIeds1", "SETIhelperless", "SETIadrs", "SETInrg1"), labels=c(expression("SETI"), expression("SETI" ~ italic("eds1")), expression("SETI" ~ italic("helperless")), expression("SETI" ~ italic("adr1s")), expression("SETI" ~ italic("nrgs"))))


test = ggplot_build(plot1)

plot1_4 = plot1 + geom_text(data = tibble(x_len = 1:10), x = test[["data"]][[1]][["x"]], y= test[["data"]][[1]][["ymax"]] + 0.45, label = sig_ordered$sig_letter, size = 3, color = "black", inherit.aes = FALSE) + 
  geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype = "dashed", alpha = 0.25)

print(plot1_4)
```

```{r Printing, include=FALSE, echo = FALSE, eval = FALSE, message = FALSE}

png(file="helperless.png",
    width=1182, height=829, res = 120)
plot1_4
dev.off()

ggsave("legend.pdf", plot = plot1_4, units = "in", width = 7.5,
  height = 3.25)
```

