---
title: "Ion_leakage_lipase"
author: "HHN"
date: "2023-11-13"
output: html_document
---

## Library used here:

```{r Library, include=TRUE, echo=TRUE, message=FALSE}
library("ggplot2")
library("tibble")
library("tidyr")
library("ggpubr")
library("multcompView")
```


# Single timepoints 24 h
## Read Files

```{r Read Files, include=TRUE, echo=TRUE, message=FALSE}
electro_leakage <- read.csv2(file = "./Data/Lipase_combine.csv", header = TRUE, dec = ",", sep = ";", fileEncoding="UTF-8-BOM")
electro_leakage = electro_leakage[,1:3]
electro_leakage_2 = as_tibble(electro_leakage)
names(electro_leakage_2) = c("sample", "value", "batch")
```

## Rearrange Data

```{r Rearrange file format, include=TRUE, echo=TRUE, message=FALSE}
el6 = separate(electro_leakage_2, "sample", sep = "_", into = c("Line_Treatment", "Time_Sample"), extra = "merge")
el7 = separate(el6, "Time_Sample", sep = "_", into = c("Time", "Sample"), extra = "merge")
el8 = unite(el7, Line_Treatment, Time, col = "Line_Treatment_Time", sep = "_")
el8 = na.omit(el8)
el9 = aggregate(el8$value, list(el8$Line_Treatment_Time), mean)
sd_val = aggregate(el8$value, list(el8$Line_Treatment_Time), sd)
names(sd_val) = c("Group.1", "SD")
combine = cbind(el9, sd_val$SD)
names(combine) = c("Line_Treatment_Time", "Mean", "SD")

el10 = separate(combine, "Line_Treatment_Time", sep = "_", into = c("Line_Treatment", "Time"), extra = "merge")
el10$Time = gsub("h", "", el10$Time)
el10$Time = as.numeric(el10$Time)

el11 = el7
el11$Time = gsub("h", "", el11$Time)
el11$Time = as.numeric(el11$Time)

seti_24_stats = el11[el11$Time == 24,]

el12 = el11[el11$Time == 24,]
el12 = separate(el11, "Line_Treatment", sep = "\\(", into = c("Line", "Treatment"), extra = "merge")
el12= na.omit(el12)
el12$Line = factor(el12$Line)
el12$Treatment = factor(el12$Treatment, levels = c("m)", "E)"))
el12$Line = sub("SETI", "SETI ", el12$Line)
el12$Line = sub("pad4sag101", "pad4 sag101", el12$Line)
levels(factor(el12$Line))
el12$Line = factor(el12$Line,  levels = c("SETI ", "SETI eds1", "SETI pad4 sag101", "SETI pad4", "SETI sag101"))
el12$shapes = rep(NA, length(el12$Line))
el12$shapes[el12$batch == "A1"] = 21
el12$shapes[el12$batch == "A3"] = 24
```

## Statistics for 24 h

```{r Statistics 24 hours, include=TRUE, echo=TRUE, message=FALSE}
# activity_treatment = aov(seti_24_stats$value ~ seti_24_stats$Line_Treatment)
# summary(aov(seti_24_stats$value ~ seti_24_stats$Line_Treatment))
# 
# Tuckey <- TukeyHSD(activity_treatment)
# test_value <- HSD.test(activity_treatment, "seti_24_stats$Line_Treatment", group = TRUE,
#                        console=TRUE)
# 
# sig = data.frame(Line = row.names(test_value[[5]]), sig_letter = test_value[[5]][[2]])
# sig$Line = factor(sig$Line, levels = c("SETI(m)", "SETI(E)", "SETIeds1(m)", "SETIeds1(E)", "SETIpad4sag101(m)", "SETIpad4sag101(E)", 
#                                       "SETIpad4(m)", "SETIpad4(E)", "SETIsag101(m)", "SETIsag101(E)"))
# line_order = order(sig$Line, levels = c("SETI(m)", "SETI(E)", "SETIeds1(m)", "SETIeds1(E)", "SETIpad4sag101(m)", "SETIpad4sag101(E)", 
#                                         "SETIpad4(m)", "SETIpad4(E)", "SETIsag101(m)", "SETIsag101(E)"))
# sig_ordered = sig[line_order,]

# New way
seti_24_stats = separate_wider_delim(seti_24_stats, cols = Line_Treatment, delim = "(", names = c("Line", "Treatment"))

activity_treatment = aov(seti_24_stats$value ~ factor(seti_24_stats$Line)*factor(seti_24_stats$Treatment) + factor(seti_24_stats$batch))
summary(aov(seti_24_stats$value ~ seti_24_stats$Line*seti_24_stats$Treatment + seti_24_stats$batch))

Tuckey <- TukeyHSD(activity_treatment)

test_value = multcompLetters4(activity_treatment, Tuckey)

sig = data.frame(Line = names(test_value$`factor(seti_24_stats$Line):factor(seti_24_stats$Treatment)`[[1]]), sig_letter = test_value$`factor(seti_24_stats$Line):factor(seti_24_stats$Treatment)`[[1]] )
sig$Line = factor(sig$Line, levels = c("SETI:m)", "SETI:E)", "SETIeds1:m)", "SETIeds1:E)", "SETIpad4sag101:m)", "SETIpad4sag101:E)", 
                                      "SETIpad4:m)", "SETIpad4:E)", "SETIsag101:m)", "SETIsag101:E)"))
line_order = order(sig$Line, levels = c("SETI:m)", "SETI:E)", "SETIeds1:m)", "SETIeds1:E)", "SETIpad4sag101:m)", "SETIpad4sag101:E)", 
                                        "SETIpad4:m)", "SETIpad4:E)", "SETIsag101:m)", "SETIsag101:E)"))
sig_ordered = sig[line_order,]

print(summary(aov(seti_24_stats$value ~ seti_24_stats$Line*seti_24_stats$Treatment + seti_24_stats$batch)))
print(Tuckey)
print(test_value )

```

## Plotting graphs

```{r Statistics single timepoint, include=TRUE, echo=TRUE, message=FALSE}
######################## Boxplot Line Treatment separate

#################Part1 Image size: 1182×829

el12$shapes[el12$batch == "A4"] = 23

dlab_theme = theme(axis.title.y = element_text(margin = margin(r = 10)), text = element_text(size=12), axis.text = element_text(size=12),
        axis.text.x = element_text(margin = margin(t = 5), size = 12, colour = "black", angle = 20, hjust=1),
        axis.text.y = element_text(color = "black"),
        axis.line = element_blank(),
        axis.ticks = element_line(size = 1),
        axis.title.x = element_blank(),
        legend.position="none", 
        legend.text= element_text(size = 12),
        #legend.title = element_text(size = 16, face = "bold"),
        panel.background = element_blank(),
        panel.spacing.x = unit(1, "lines"),
        panel.spacing.y=unit(0,"lines"),
        panel.grid =  element_blank(),
        legend.title = element_blank(),
        #panel.grid.major.y =  element_line(colour = "#999999"),
        panel.grid.minor.y =  element_blank(),
        panel.border = element_rect(fill = NA, color = "black", linewidth = 1),
        strip.background =element_rect(fill="white"),
        strip.text.x = element_text(size = 12, hjust = 0.5))

plot1_4 = ggplot(el12[el12$Time == 24,], aes(y = value, x = Line))  +
  geom_boxplot(aes(fill = Treatment), outlier.shape = NA) +
  geom_jitter(mapping = aes(shape = batch, color = Treatment, group = Treatment), fill = "grey", size=1.5, position = position_jitterdodge(jitter.width = 0.3, dodge.width = 0.75)) +
  ylim(8,30) +
  scale_fill_manual(values = c("#F93D3D",  "#0072B2"),
                    name = "Treatments", labels = c("Mock", "ETI"))  +
  scale_shape_manual(name = "Batches",  values = unique(el12$shapes), labels = c("B1", "B2", "B3")) +
  scale_color_manual(values = c("black", "black")) +
  guides(color = FALSE) +
  #scale_shape_discrete(position = position_identity()) +
  labs(y = "Conductivity\n(µS/cm)", x = "Line") + dlab_theme +
  scale_x_discrete(breaks = c("SETI ", "SETI eds1", "SETI pad4 sag101", "SETI pad4", "SETI sag101"), labels=c(expression("SETI wt"), expression("SETI" ~ italic("eds1")), expression("SETI" ~ italic("pad4 sag101")), expression("SETI" ~ italic("pad4")), expression("SETI" ~ italic("sag101"))))

test = ggplot_build(plot1_4)

plot1_4 = plot1_4 +
  annotate(geom = "text", x = test[["data"]][[1]][["x"]], y= test[["data"]][[1]][["ymax"]] + 0.9, label = sig_ordered$sig_letter, size = 3, color = "black") +
  geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype = "dashed", alpha = 0.25)

print(plot1_4)
```


```{r Printing Plot 1, include=TRUE, echo=TRUE, message=FALSE, eval=FALSE}
png(file="lipase_combined_batch_24h.png",
    width=1182, height=829, res = 120)
plot1_4
dev.off()

ggsave("lipase_24_ion_leakage.pdf", units = "in", width = 4,
  height = 3.25)

```

# Multiple timepoints 0 h to 8 h
## Plot 3 boxplot for multiple timepoints

```{r Boxplots multiple timepoints, include=TRUE, echo=TRUE, message=FALSE}

labeller = labeller(Time = 
                      c("0" = "0 h",
                        "2" = "2 h",
                        "4" = "4 h",
                        "6" = "6 h",
                        "8" = "8 h",
                        "22" = "22 h"))

plot1_3 = ggplot(el12[el12$Time < 24,], aes(y = value, x = Line, fill = Treatment)) +
  geom_boxplot(aes(fill = Treatment), outlier.shape = NA) +
  geom_jitter(mapping = aes(shape = batch, color = Treatment, group = Treatment), fill = "grey", size=1, position = position_jitterdodge(jitter.width = 0.3, dodge.width = 0.75 )) +
  ylim(5,30) +
  scale_fill_manual(values = c("#F93D3D",  "#0072B2"),
                    name = "Treatment", labels = c("Mock", "ETI"))  +
  scale_shape_manual(values = unique(el12$shapes)) +
  scale_color_manual(values = c("black", "black")) +
  labs(y = "Conductivity\n[µS/cm]", x = "Line") +
  dlab_theme +
  scale_x_discrete(breaks = c("SETI ", "SETI eds1", "SETI pad4 sag101", "SETI pad4", "SETI sag101"), labels=c(expression("SETI wt"), expression("SETI" ~ italic("eds1")), expression("SETI" ~ italic("pad4 sag101")), expression("SETI" ~ italic("pad4")), expression("SETI" ~ italic("sag101")))) + 
  facet_wrap(.~Time, scales="free_y", labeller = labeller)

test1_3 = ggplot_build(plot1_3)
```

# Statistics

```{r Statistics boxplots multiple timepoints statistics, include=TRUE, echo=TRUE, message=FALSE}

stats_table = data.frame(Line_treatment = NA,
                         sig_letters = NA, timepoint = NA)
el12$batch = factor(el12$batch)
el12$Line = factor(el12$Line)
el12$Treatment = factor(el12$Treatment)

for (timepoints in unique(el12$Time[el12$Time != 24])) {
  activity_treatment = aov(el12[el12$Time == timepoints,]$value ~ el12[el12$Time == timepoints,]$Line*el12[el12$Time == timepoints,]$Treatment + el12[el12$Time == timepoints,]$batch)
  summary(activity_treatment)
  Tuckey <- TukeyHSD(activity_treatment)
  stats = multcompLetters4(activity_treatment, Tuckey)
  time = rep(timepoints, length(stats[["el12[el12$Time == timepoints, ]$Line:el12[el12$Time == timepoints, ]$Treatment"]][[1]]))
  line_treatment = names(stats[["el12[el12$Time == timepoints, ]$Line:el12[el12$Time == timepoints, ]$Treatment"]][[1]])
  sig_letters = stats[["el12[el12$Time == timepoints, ]$Line:el12[el12$Time == timepoints, ]$Treatment"]][[1]]
  print("--------------------------------------------------------------------------------------")
  print(timepoints)
  print(summary)
  print(Tuckey)
  print(stats)
   print("--------------------------------------------------------------------------------------")
  help_table = data.frame(Line_treatment = line_treatment,
                          sig_letters = sig_letters, timepoint = time)
  stats_table = rbind(stats_table, help_table)
  stats_table = na.omit(stats_table)
}

stats_table$Line_treatment = factor(stats_table$Line_treatment, levels = c("SETI :m)", "SETI :E)", "SETI eds1:m)", "SETI eds1:E)",
                                              "SETI pad4 sag101:m)", "SETI pad4 sag101:E)", "SETI pad4:m)", "SETI pad4:E)",
                                              "SETI sag101:m)", "SETI sag101:E)"))


line_treatment_order = order(factor(stats_table$Line_treatment))
stats_table_1 = stats_table[line_treatment_order,]
stats_table_2 = stats_table_1[order(stats_table_1$timepoint),]

```

```{r Boxplots multiple timepoints statistics}

plot1_4 = plot1_3 +
  geom_text(data = tibble(test = 1:10), x = test1_3[["data"]][[1]][["x"]], y = test1_3[["data"]][[1]][["ymax"]] + 1.75, label = stats_table_2$sig_letters, size = 3, color = "black", inherit.aes = FALSE) +
  geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype = "dashed", alpha = 0.25)

print(plot1_4)
```

```{r Print boxplots multiple timepoints statistics, include=FALSE, eval=FALSE}

ggsave("lipase_combined_batch_timepoints.pdf", plot = plot1_4, units = "in", width = 8,
  height = 6.5)

```